# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eror_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys


from PyQt5.QtGui import *
from PyQt5.QtGui import *
from PyQt5.QtGui import *
from pyqt5_plugins import *

from PySide6.QtCore import *
from PySide6.QtUiTools import loadUiType
from PySide6.QtWidgets import *

import cv2

ui2, _ = loadUiType("get_data.ui")


class UI_get_data(QMainWindow, ui2):
    global widgets
    widgets_eror = ui2
    image_glob=0
    close_sign=0
    def __init__(self):
        super(UI_get_data, self).__init__()
        self.setupUi(self)
        # Remove default frame
        flags = Qt.WindowFlags(Qt.FramelessWindowHint | Qt.WindowStaysOnTopHint)
        self.pos_ = self.pos()
      #  self.confirm_btn.set
        self.setWindowFlags(flags)
        # self.set_shape()
        self.activate_()
        
    def set_shape(self):

        image=cv2.imread('images\check-mark.png')

        self.image = QImage(image,image.shape[1], image.shape[0],image.strides[0], QImage.Format_BGR888 )
        
        self.confirm_btn.setPixmap(QPixmap.fromImage(self.image)) 


    def activate_(self):
        self.close_btn.clicked.connect(self.close_win)
    def close_win(self):
        self.close_sign=1
        self.close()

if __name__ == "__main__":
    app = QApplication()
    win = UI_get_data()
    win.show()
    sys.exit(app.exec())
